name: build/node-pnpm

on:
  push:
    branches:
      - main
    paths:
      - images/node-pnpm/**
      - .github/workflows/build-node-pnpm.yaml

  schedule:
    - cron: "0 3 * * 1"

  workflow_dispatch:

jobs:
  build-and-push:
    uses: rizuke/.github/.github/workflows/build-docker-image.yaml@main
    with:
      image-name: node-pnpm
      context: ./images/node-pnpm
      dockerfile: ./images/node-pnpm/Dockerfile
      multi-arch: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write