name: Build devcontainer image node-pnpm

on:
  push:
    branches:
      - main
    paths:
      - images/node-pnpm/**
      - .github/workflows/build-node-pnpm.yml

  schedule:
    - cron: "0 3 * * 1"

  workflow_dispatch:

jobs:
  build-and-push:
    uses: rizuke/.github/workflows/build-docker-image.yml@main
    with:
      image-name: node-pnpm
      context: ./images/node-pnpm
      dockerfile: ./images/node-pnpm/Dockerfile
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}